-- Run as a privileged local development account in FREEPDB1.
-- Passwords are placeholders for Phase 1 and must be supplied securely before execution.
WHENEVER SQLERROR EXIT SQL.SQLCODE;

CREATE USER zc_stage IDENTIFIED BY "CHANGE_ME_STAGE" QUOTA UNLIMITED ON users;
CREATE USER zc_dw IDENTIFIED BY "CHANGE_ME_DW" QUOTA UNLIMITED ON users;
CREATE USER zc_audit IDENTIFIED BY "CHANGE_ME_AUDIT" QUOTA UNLIMITED ON users;
CREATE USER zc_dbt IDENTIFIED BY "CHANGE_ME_DBT" QUOTA UNLIMITED ON users;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO zc_stage;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE SEQUENCE TO zc_dw;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO zc_audit;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW TO zc_dbt;

-- Apply object-level grants only after 002_core_objects.sql creates the tables.
