-- Run as ADMIN in SQL Developer with F5. Password input is hidden.
-- Autonomous Database: do not use ALTER SESSION SET CONTAINER.
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET VERIFY OFF

CREATE USER zc_stage NO AUTHENTICATION
    DEFAULT TABLESPACE data QUOTA 1G ON data;
CREATE USER zc_audit NO AUTHENTICATION
    DEFAULT TABLESPACE data QUOTA 500M ON data;
CREATE USER zc_dw NO AUTHENTICATION
    DEFAULT TABLESPACE data QUOTA 2G ON data;

GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO zc_stage;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO zc_audit;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
      CREATE MATERIALIZED VIEW, CREATE PROCEDURE TO zc_dw;

ACCEPT ingest_password CHAR PROMPT 'Password for ZC_INGEST: ' HIDE
CREATE USER zc_ingest IDENTIFIED BY "&ingest_password"
    DEFAULT TABLESPACE data QUOTA 0 ON data;
UNDEFINE ingest_password

ACCEPT dbt_password CHAR PROMPT 'Password for ZC_DBT: ' HIDE
CREATE USER zc_dbt IDENTIFIED BY "&dbt_password"
    DEFAULT TABLESPACE data QUOTA 2G ON data;
UNDEFINE dbt_password

GRANT CREATE SESSION TO zc_ingest;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW,
      CREATE MATERIALIZED VIEW, CREATE SEQUENCE TO zc_dbt;
SET VERIFY ON

