-- Run as ADMIN after 001_create_zambecare_users.sql.
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE zc_audit.etl_batch (
    batch_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    source_system VARCHAR2(50) NOT NULL,
    entity_name VARCHAR2(50) NOT NULL,
    start_watermark TIMESTAMP WITH TIME ZONE,
    end_watermark TIMESTAMP WITH TIME ZONE,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    batch_status VARCHAR2(20) DEFAULT 'STARTED' NOT NULL,
    source_count NUMBER DEFAULT 0 NOT NULL,
    staged_count NUMBER DEFAULT 0 NOT NULL,
    rejected_count NUMBER DEFAULT 0 NOT NULL,
    retry_count NUMBER DEFAULT 0 NOT NULL,
    code_version VARCHAR2(100),
    error_message VARCHAR2(2000),
    CONSTRAINT pk_etl_batch PRIMARY KEY (batch_id),
    CONSTRAINT ck_etl_batch_status CHECK (batch_status IN
      ('STARTED','EXTRACTING','VALIDATING','LOADING','RECONCILING','COMPLETED','FAILED')),
    CONSTRAINT ck_etl_batch_counts CHECK
      (source_count >= 0 AND staged_count >= 0 AND rejected_count >= 0 AND retry_count >= 0)
);

CREATE TABLE zc_audit.extraction_watermark (
    source_system VARCHAR2(50) NOT NULL,
    entity_name VARCHAR2(50) NOT NULL,
    last_success_watermark TIMESTAMP WITH TIME ZONE,
    last_batch_id NUMBER,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_extraction_watermark PRIMARY KEY (source_system, entity_name),
    CONSTRAINT fk_watermark_batch FOREIGN KEY (last_batch_id)
      REFERENCES zc_audit.etl_batch(batch_id)
);

CREATE TABLE zc_audit.rejected_record (
    rejection_id NUMBER GENERATED ALWAYS AS IDENTITY,
    batch_id NUMBER NOT NULL,
    source_entity VARCHAR2(50) NOT NULL,
    source_record_id VARCHAR2(100),
    rule_code VARCHAR2(100) NOT NULL,
    rejection_reason VARCHAR2(2000) NOT NULL,
    raw_payload CLOB,
    record_checksum VARCHAR2(64),
    rejected_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_rejected_record PRIMARY KEY (rejection_id),
    CONSTRAINT fk_rejected_batch FOREIGN KEY (batch_id)
      REFERENCES zc_audit.etl_batch(batch_id),
    CONSTRAINT ck_rejected_payload_json CHECK (raw_payload IS JSON)
);

CREATE TABLE zc_audit.reconciliation_result (
    reconciliation_id NUMBER GENERATED ALWAYS AS IDENTITY,
    batch_id NUMBER NOT NULL,
    entity_name VARCHAR2(50) NOT NULL,
    source_count NUMBER NOT NULL,
    staged_count NUMBER NOT NULL,
    rejected_count NUMBER NOT NULL,
    unexplained_count NUMBER NOT NULL,
    reconciliation_status VARCHAR2(10) NOT NULL,
    checked_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_reconciliation_result PRIMARY KEY (reconciliation_id),
    CONSTRAINT fk_reconciliation_batch FOREIGN KEY (batch_id)
      REFERENCES zc_audit.etl_batch(batch_id),
    CONSTRAINT ck_reconciliation_status CHECK (reconciliation_status IN ('PASS','FAIL')),
    CONSTRAINT ck_reconciliation_counts CHECK
      (source_count >= 0 AND staged_count >= 0 AND rejected_count >= 0)
);

CREATE INDEX zc_audit.ix_rejected_batch ON zc_audit.rejected_record(batch_id);
CREATE INDEX zc_audit.ix_recon_batch ON zc_audit.reconciliation_result(batch_id);

